CREATE TABLE IF NOT EXISTS PUBLIC.MPA (
                                          MPA_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
                                            FILM_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            NAME VARCHAR(255) NOT NULL,
                                            MPA_ID INT NOT NULL,
                                            DESCRIPTION VARCHAR(255) NOT NULL,
                                            RELEASE_DATE DATE NOT NULL,
                                            DURATION BIGINT NOT NULL,
                                            FOREIGN KEY (MPA_ID) REFERENCES PUBLIC.MPA(MPA_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
                                             GENRE_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRES (
                                                  FILM_ID INT NOT NULL,
                                                  GENRE_ID INT NOT NULL,
                                                  PRIMARY KEY (FILM_ID, GENRE_ID),
                                                  FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID),
                                                  FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRES(GENRE_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
                                            USER_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            EMAIL VARCHAR(255) NOT NULL,
                                            LOGIN VARCHAR(255) NOT NULL,
                                            NAME VARCHAR(255) NOT NULL,
                                            BIRTHDAY DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_LIKES (
                                                 FILM_ID INT,
                                                 USER_ID INT,
                                                 PRIMARY KEY (FILM_ID, USER_ID),
                                                 FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID),
                                                 FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USER_FRIENDS (
                                                   USER_ID INT NOT NULL,
                                                   FRIEND_ID INT NOT NULL,
                                                   APPLIED BOOLEAN NOT NULL,
                                                   PRIMARY KEY (USER_ID, FRIEND_ID, APPLIED),
                                                   FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID),
                                                   FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(USER_ID)
);